# Minecraft Java Paper Server + The Curse Plugin Docker Container
# https://github.com/TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate
services:
  minecraftbe:
    image: 05jchambers/legendary-minecraft-geyser-floodgate:latest
    restart: "unless-stopped"
    ports:
      - 25565:25565
      - 19132:19132
      - 19132:19132/udp
    volumes:
      - minecraft:/minecraft
      - ./target/curse-0.1.2.jar:/minecraft/plugins/curse-0.1.2.jar
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: ["/bin/bash", "/scripts/start.sh"]
    environment:
      Port: "25565"
      BedrockPort: "19132"
      TZ: "America/New_York"
      MaxMemory: 4096
      Version: "1.21.6" # Force latest Paper version
      NoBackup: "plugins" # Optional folder to skip during backups
      NoPermCheck: "Y" # Optional flag to skip permissions check
      # NoViaVersion: "Y" # Enable ViaVersion for Geyser compatibility
      QuietCurl: "Y" # Optional flag to reduce curl log output
volumes:
  minecraft:
    driver: local
