# The Curse Plugin Configuration
# https://xp.farm

# Plague Configuration
plague:
  # Maximum number of rounds before final wave
  maxRounds: 7
  
  # Scale difficulty with player XP level
  scaleWithXP: true
  
  # Spawn radius around player (blocks)
  spawnRadius: 20
  
  # Time limit per round (seconds, 0 = no limit)
  timeLimitPerRound: 180
  
  # Allow mobs to damage terrain
  allowTerrainDamage: false
  
  # Maximum number of active plagues on server
  maxActivePlagues: 3
  
  # Enable visual effects (particles, sounds)
  visualEffects: true
  
  # Combat radius - leaving this area applies poison but continues curse
  combatRadius: 30
  
  # Warning distance - warn player when they get this close to the boundary
  warningDistance: 5
  
  # Warning cooldown - seconds between warnings to prevent spam
  warningCooldownSeconds: 10
  
  # Minimum distance from villages/protected areas
  minDistanceFromVillages: 100
  
  # Cooldown after curse reset (minutes)
  resetCooldownMinutes: 5

# Cursed Book Configuration
cursedBook:
  # Enable the cursed book feature
  enabled: true
  
  # Maximum range for zombie to detect dropped book (blocks)
  pickupRange: 10
  
  # Enable recipe for crafting cursed books
  enableRecipe: true
  
  # Enable visual effects when curse is activated via book
  enableActivationEffects: true

# HUD Configuration
hud:
  # Enable HUD display for plague information
  enabled: true
  
  # Update interval in ticks (20 ticks = 1 second)
  updateInterval: 20
  
  # Show timer countdown (requires timeLimitPerRound > 0)
  showTimer: true
  
  # Show kill count
  showKills: true
  
  # Show remaining mobs in current round
  showRemainingMobs: true
  
  # Show antidote status
  showAntidoteStatus: true

# Rewards Configuration
rewards:
  # Loot that can appear in reward chests
  chestLoot:
    common:
      - "minecraft:bread"
      - "minecraft:cooked_beef"
      - "minecraft:golden_apple"
    uncommon:
      - "minecraft:potion{Potion:\"minecraft:healing\"}"
      - "minecraft:potion{Potion:\"minecraft:swiftness\"}"
      - "minecraft:enchanted_book"
    rare:
      - "minecraft:totem_of_undying"
      - "minecraft:netherite_ingot"
      - "minecraft:diamond"
    legendary:
      - "curse:undo_potion"
      - "minecraft:dragon_egg"

# Leaderboard Configuration
leaderboard:
  # Enable leaderboard system
  enabled: true
  
  # Metrics to track
  trackMetrics:
    - "totalCompletions"
    - "bestTime"
    - "totalKills"
    - "highestRound"
  
  # Number of entries to display
  displayCount: 10

# Debug Configuration
debug:
  # Enable debug messages
  enabled: false
  
  # Log mob spawn events
  logMobSpawns: false
  
  # Log player actions
  logPlayerActions: false
